/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_victorvalladares_12141026;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author valla
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        presets();
    }
    
    ArrayList <Planeta> lista = new ArrayList();
    
    private void presets(){
        Planeta marte = new Planeta ("Marte", true, 30000, 10);
        Planeta io = new Planeta ("Io", true, 10000, 5);
        Planeta Jupiter = new Planeta("Jupiter", false, 500000, -20);
        
        Raza hive = new Raza (io, "Hive");
        Raza fallen = new Raza (marte, "Eliksni");
        
        Cazador Oryx = new Cazador (20, "Oryx", hive, 20, true);
        Abduzcan Taniks = new Abduzcan (200, "Taniks", fallen, 50, true);
        
        marte.getHabitantes().add(Oryx);
        marte.getHabitantes().add(Taniks);
        
        Conquistador Savathun = new Conquistador("Savathun", hive, 200, true);
        Savathun.getConquistados().add(Jupiter);
        
        Explorador Mithrax = new Explorador (marte, "Mithrax", fallen, 75, false);
        
        io.getHabitantes().add(Savathun);
        io.getHabitantes().add(Mithrax);
        
        DefaultComboBoxModel cb_model =
                    (DefaultComboBoxModel) cb_planetas.getModel();
        cb_model.addElement(marte);
        cb_model.addElement(io);
        cb_model.addElement(Jupiter);
        
        cb_planetas.setModel(cb_model);
        cb_planetas_arb.setModel(cb_model);
        cb_favorito.setModel(cb_model);
        cb_planetafav_editar.setModel(cb_model);
        cb_habita_exp.setModel(cb_model);
        cb_habita_con.setModel(cb_model);
        cb_habita_caz.setModel(cb_model);
        cb_habita_ab.setModel(cb_model);
        
        DefaultListModel listaModelo = 
                (DefaultListModel)jL_planetas.getModel();
        listaModelo.removeAllElements();
        listaModelo.addElement(marte);
        listaModelo.addElement(io);
        listaModelo.addElement(Jupiter);
        
        jL_planetas.setModel(listaModelo);
        jL_planetas_con.setModel(listaModelo);
        jL_planetas_disp.setModel(listaModelo);
        
        DefaultComboBoxModel cb_model_raza =
                    (DefaultComboBoxModel) cb_raza_exp.getModel();
        cb_model_raza.addElement(hive);
        cb_model_raza.addElement(fallen);

        cb_raza_exp.setModel(cb_model_raza);
        cb_raza_caz.setModel(cb_model_raza);
        cb_raza_con.setModel(cb_model_raza);
        cb_raza_ab.setModel(cb_model_raza);
        cb_raza_editar.setModel(cb_model_raza);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_nombre_p = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        js_temperatura = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        js_size = new javax.swing.JSpinner();
        jc_agua = new javax.swing.JCheckBox();
        jb_guardar_p = new javax.swing.JButton();
        cb_planetas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre_r = new javax.swing.JTextField();
        jb_guardar_r = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombre_exp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_planetas = new javax.swing.JList<>();
        jb_agregar_exp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jL_explorados = new javax.swing.JList<>();
        jc_amenaza_exp = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        cb_raza_exp = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cb_favorito = new javax.swing.JComboBox<>();
        jb_guardar_exp = new javax.swing.JButton();
        js_edad_exp = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        cb_habita_exp = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tf_nombre_caz = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        js_edad_caz = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        cb_raza_caz = new javax.swing.JComboBox<>();
        jc_amenaza_caz = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        js_humanos = new javax.swing.JSpinner();
        jb_guardar_caz = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        cb_habita_caz = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tf_nombre_con = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        js_edad_con = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        cb_raza_con = new javax.swing.JComboBox<>();
        jc_amenaza_con = new javax.swing.JCheckBox();
        jb_guardar_con = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jL_planetas_con = new javax.swing.JList<>();
        jb_agregar_con = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jL_conquistados = new javax.swing.JList<>();
        jLabel32 = new javax.swing.JLabel();
        cb_habita_con = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        tf_nombre_ab = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        js_edad_ab = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        cb_raza_ab = new javax.swing.JComboBox<>();
        jc_amenaza_ab = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        js_animales = new javax.swing.JSpinner();
        jb_guardar_ab = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        cb_habita_ab = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        cb_planetas_arb = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jL_alien = new javax.swing.JList<>();
        jb_pasar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        jLabel24 = new javax.swing.JLabel();
        tf_nombre_editar = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cb_planetafav_editar = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        js_edad_editar = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        cb_raza_editar = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        js_humanos_editar = new javax.swing.JSpinner();
        js_animales_editar = new javax.swing.JSpinner();
        jc_amenaza_editar = new javax.swing.JCheckBox();
        jb_editar = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jL_planetas_disp = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jL_planetas_disp1 = new javax.swing.JList<>();
        jb_pasar_editar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jTabbedPane3.addTab("tab1", jTabbedPane4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Discovery Channel");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Planetas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Razas");

        jLabel1.setText("Nombre");

        jLabel4.setText("Temperatura");

        jLabel5.setText("Tamaño");

        jc_agua.setText("Agua");

        jb_guardar_p.setText("Registrar Planeta");
        jb_guardar_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardar_pMouseClicked(evt);
            }
        });

        jLabel6.setText("Planeta Primordial");

        jLabel7.setText("Nombre");

        jb_guardar_r.setText("Registrar Raza");
        jb_guardar_r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardar_rMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(148, 148, 148))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(js_temperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_nombre_p))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(js_size, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(184, 184, 184)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jb_guardar_r)
                                .addGap(0, 90, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(cb_planetas, 0, 128, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addComponent(tf_nombre_r))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jc_agua, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_guardar_p))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_planetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_nombre_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_guardar_r))
                .addGap(31, 31, 31)
                .addComponent(jc_agua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_guardar_p)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Planetas y Razas", jPanel1);

        jLabel8.setText("Nombre");

        jLabel9.setText("Edad");

        jL_planetas.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jL_planetas);

        jb_agregar_exp.setText("Añadir a su lista");
        jb_agregar_exp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregar_expMouseClicked(evt);
            }
        });

        jL_explorados.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jL_explorados);

        jc_amenaza_exp.setText("Es amenaza");

        jLabel10.setText("Raza");

        jLabel11.setText("Planeta Favorito");

        jb_guardar_exp.setText("Guardar");
        jb_guardar_exp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardar_expMouseClicked(evt);
            }
        });

        jLabel30.setText("Planeta que habitan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(169, 169, 169))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(js_edad_exp)
                                .addGap(83, 83, 83)))
                        .addComponent(jc_amenaza_exp))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_agregar_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nombre_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel8)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(cb_raza_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jb_guardar_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cb_favorito, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(cb_habita_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_favorito, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_raza_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_guardar_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jc_amenaza_exp))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(js_edad_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jb_agregar_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_habita_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
        );

        jTabbedPane1.addTab("Explorador", jPanel2);

        jLabel13.setText("Nombre");

        jLabel14.setText("Edad");

        jLabel15.setText("Raza");

        jc_amenaza_caz.setText("Es amenaza");

        jLabel16.setText("Humanos atrapados");

        jb_guardar_caz.setText("Guardar");
        jb_guardar_caz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardar_cazMouseClicked(evt);
            }
        });

        jLabel31.setText("Planeta que habita");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(tf_nombre_caz, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(js_edad_caz, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(95, 95, 95)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15)
                                .addComponent(cb_raza_caz, 0, 173, Short.MAX_VALUE)
                                .addComponent(jLabel31)
                                .addComponent(cb_habita_caz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(11, 11, 11))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                            .addComponent(js_humanos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jb_guardar_caz, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jc_amenaza_caz)
                .addGap(218, 218, 218))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre_caz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_raza_caz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cb_habita_caz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(js_edad_caz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jc_amenaza_caz)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_humanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(30, 30, 30)
                .addComponent(jb_guardar_caz)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cazador", jPanel3);

        jLabel17.setText("Nombre");

        jLabel18.setText("Edad");

        jLabel19.setText("Raza");

        jc_amenaza_con.setText("Es amenaza");

        jb_guardar_con.setText("Guardar");
        jb_guardar_con.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardar_conMouseClicked(evt);
            }
        });

        jL_planetas_con.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jL_planetas_con);

        jb_agregar_con.setText("Añadir a su lista");
        jb_agregar_con.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregar_conMouseClicked(evt);
            }
        });

        jL_conquistados.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jL_conquistados);

        jLabel32.setText("Planeta que habita");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel17))
                            .addComponent(tf_nombre_con, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel18))
                            .addComponent(js_edad_con, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_habita_con, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(cb_raza_con, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jc_amenaza_con))
                                .addContainerGap(151, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb_guardar_con, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jb_agregar_con))
                            .addComponent(jLabel32))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_raza_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jb_guardar_con, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jc_amenaza_con))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(js_edad_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_habita_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jb_agregar_con, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conquistador", jPanel4);

        jLabel20.setText("Nombre");

        jLabel21.setText("Edad");

        jLabel22.setText("Raza");

        jc_amenaza_ab.setText("Es amenza");

        jLabel23.setText("Animales Abducidos");

        jb_guardar_ab.setText("Guardar");
        jb_guardar_ab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardar_abMouseClicked(evt);
            }
        });

        jLabel33.setText("Planeta que habita");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf_nombre_ab, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel21))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(js_edad_ab)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addGap(207, 207, 207))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jc_amenaza_ab))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel33)
                                    .addComponent(cb_raza_ab, 0, 156, Short.MAX_VALUE)
                                    .addComponent(cb_habita_ab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel23)
                        .addGap(46, 46, 46)
                        .addComponent(js_animales, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jb_guardar_ab, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre_ab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_raza_ab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel21))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_habita_ab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(js_edad_ab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_amenaza_ab))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(js_animales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jb_guardar_ab)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Abduzcan", jPanel5);

        jL_alien.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jL_alien);

        jb_pasar.setText(">");

        jScrollPane6.setViewportView(jt_arbol);

        jLabel24.setText("Nombre");

        jLabel26.setText("Planeta Favorito");

        jLabel28.setText("Edad");

        jLabel25.setText("Raza");

        jLabel27.setText("Humanos Atrapados");

        jLabel29.setText("Animales Abducidos");

        jc_amenaza_editar.setText("Es Amenaza");

        jb_editar.setText("Editar");

        jL_planetas_disp.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jL_planetas_disp);

        jL_planetas_disp1.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(jL_planetas_disp1);

        jb_pasar_editar.setText(">");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cb_planetas_arb, 0, 145, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_pasar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_pasar_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(js_humanos_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_planetafav_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_nombre_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(js_edad_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_raza_editar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel26)
                            .addComponent(jc_amenaza_editar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(js_animales_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nombre_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jc_amenaza_editar)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_planetafav_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(js_edad_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(cb_raza_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(js_humanos_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(js_animales_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jb_editar))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cb_planetas_arb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jb_pasar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jb_pasar_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arbol", jPanel6);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Registro De Alienigenas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_guardar_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardar_pMouseClicked
        String nombre;
        boolean agua = false;
        int size, temperatura;
        try{
            nombre = tf_nombre_p.getText();
            for (Planeta planetas : lista){
                if (planetas.getNombre().contains(nombre)){
                    JOptionPane.showMessageDialog(null, "Este nombre ya existe");
                    nombre = JOptionPane.showInputDialog("Ingrese otro nombre");
                }
            }
            
            if(jc_agua.isSelected()){
                agua = true;
            }
            
            size = (Integer) js_size.getValue();
            temperatura = (Integer) js_temperatura.getValue();
            Planeta x = new Planeta (nombre, agua, size, temperatura);
            lista.add(x);
            
            DefaultComboBoxModel cb_model =
                    (DefaultComboBoxModel) cb_planetas.getModel();
            cb_model.addElement(x);
            
            cb_planetas.setModel(cb_model);
            cb_planetas_arb.setModel(cb_model);
            cb_favorito.setModel(cb_model);
            cb_planetafav_editar.setModel(cb_model);
            cb_habita_exp.setModel(cb_model);
            cb_habita_con.setModel(cb_model);
            cb_habita_caz.setModel(cb_model);
            cb_habita_ab.setModel(cb_model);
            
            DefaultListModel listaModelo = (DefaultListModel)jL_planetas.getModel();
            listaModelo.removeAllElements();
            listaModelo.addElement(x);
            jL_planetas.setModel(listaModelo);
            jL_planetas_con.setModel(listaModelo);
            jL_planetas_disp.setModel(listaModelo);
            
            
            tf_nombre_p.setText("");
            jc_agua.setSelected(false);
            js_size.setValue(0);
            js_temperatura.setValue(0);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "No se ha podido guardar el planeta");
        }    
    }//GEN-LAST:event_jb_guardar_pMouseClicked

    private void jb_guardar_rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardar_rMouseClicked
        Planeta primordial;
        String nombre;
        try{
            primordial = (Planeta) cb_planetas.getSelectedItem();
            nombre = tf_nombre_r.getText();
            Raza x = new Raza (primordial, nombre);
            
            DefaultComboBoxModel cb_model =
                    (DefaultComboBoxModel) cb_raza_exp.getModel();
            cb_model.addElement(x);
            
            cb_raza_exp.setModel(cb_model);
            cb_raza_caz.setModel(cb_model);
            cb_raza_con.setModel(cb_model);
            cb_raza_ab.setModel(cb_model);
            cb_raza_editar.setModel(cb_model);
            
            tf_nombre_r.setText("");
            
            
        }catch (Exception ex){  
        }
    }//GEN-LAST:event_jb_guardar_rMouseClicked

    private void jb_guardar_expMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardar_expMouseClicked
        String nombre;
        Raza raza;
        int edad;
        Planeta favorito;
        boolean amenaza = false;
        try{
            nombre = tf_nombre_exp.getText();
            raza = (Raza)cb_raza_exp.getSelectedItem();
            edad = (Integer)js_edad_exp.getValue();
            favorito = (Planeta)cb_favorito.getSelectedItem();
            if (jc_amenaza_exp.isSelected()){
                amenaza = true;
            }
            Explorador x = new Explorador(favorito, nombre, raza, edad, amenaza);
            Planeta guardar = (Planeta)cb_habita_exp.getSelectedItem();
            guardar.getHabitantes().add(x);
            
           
            
            DefaultListModel listaModelo = (DefaultListModel)jL_explorados.getModel();
            int length = listaModelo.getSize();
            
            if (!(length < 0)){
                for (int i = 0; i < length; i++){
                    x.getPlanetas().add((Planeta)listaModelo.getElementAt(i));
                }
            }
            
            tf_nombre_exp.setText("");
            js_edad_exp.setValue(0);
            jc_amenaza_exp.setSelected(false);
            listaModelo.removeAllElements();
            jL_explorados.setModel(listaModelo);
            
        }catch(Exception ex){   
        }
        
    }//GEN-LAST:event_jb_guardar_expMouseClicked

    private void jb_guardar_cazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardar_cazMouseClicked
        String nombre;
        Raza raza;
        int edad;
        int humanos;
        boolean amenaza = false;
        try{
            nombre = tf_nombre_caz.getText();
            raza = (Raza)cb_raza_caz.getSelectedItem();
            edad = (Integer)js_edad_caz.getValue();
            humanos = (Integer)js_humanos.getValue();
            
            if (jc_amenaza_caz.isSelected()){
                amenaza = true;
            }
            Cazador x = new Cazador(humanos, nombre, raza, edad, amenaza);
            Planeta guardar = (Planeta) cb_habita_caz.getSelectedItem();
            guardar.getHabitantes().add(x);
            
            tf_nombre_caz.setText("");
            js_edad_caz.setValue(0);
            jc_amenaza_caz.setSelected(false);
            js_humanos.setValue(0);
            
        }catch(Exception ex){   
        }
    }//GEN-LAST:event_jb_guardar_cazMouseClicked

    private void jb_guardar_conMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardar_conMouseClicked
        String nombre;
        Raza raza;
        int edad;
        boolean amenaza = false;
        try{
            nombre = tf_nombre_con.getText();
            raza = (Raza)cb_raza_con.getSelectedItem();
            edad = (Integer)js_edad_con.getValue();
            if (jc_amenaza_exp.isSelected()){
                amenaza = true;
            }
            Conquistador x = new Conquistador(nombre, raza, edad, amenaza);
            Planeta guardar = (Planeta)cb_habita_con.getSelectedItem();
            guardar.getHabitantes().add(x);
            
            
            
            DefaultListModel listaModelo = (DefaultListModel)jL_conquistados.getModel();
            int length = listaModelo.getSize();
            
            if (!(length < 0)){
                for (int i = 0; i < length; i++){
                    x.getConquistados().add((Planeta)listaModelo.getElementAt(i));
                }
            }
            
            tf_nombre_con.setText("");
            js_edad_con.setValue(0);
            jc_amenaza_con.setSelected(false);
            listaModelo.removeAllElements();
            jL_conquistados.setModel(listaModelo);
            
        }catch(Exception ex){   
        }
    }//GEN-LAST:event_jb_guardar_conMouseClicked

    private void jb_guardar_abMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardar_abMouseClicked
        String nombre;
        Raza raza;
        int edad;
        int animales;
        boolean amenaza = false;
        try{
            nombre = tf_nombre_ab.getText();
            raza = (Raza)cb_raza_ab.getSelectedItem();
            edad = (Integer)js_edad_ab.getValue();
            animales = (Integer)js_animales.getValue();
            if (jc_amenaza_exp.isSelected()){
                amenaza = true;
            }
            Abduzcan x = new Abduzcan(animales, nombre, raza, edad, amenaza);
            Planeta guardar = (Planeta)cb_habita_ab.getSelectedItem();
            guardar.getHabitantes().add(x);
            
            tf_nombre_ab.setText("");
            js_edad_ab.setValue(0);
            jc_amenaza_ab.setSelected(false);
            js_animales.setValue(0);
        }catch(Exception ex){   
        }
    }//GEN-LAST:event_jb_guardar_abMouseClicked

    private void jb_agregar_expMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregar_expMouseClicked
       DefaultListModel listaModelo = (DefaultListModel)jL_planetas.getModel();
       Planeta mover = (Planeta) listaModelo.getElementAt(jL_planetas.getSelectedIndex());
       
       
       DefaultListModel lista = (DefaultListModel)jL_explorados.getModel();
       lista.addElement(mover);
       jL_explorados.setModel(lista);
    }//GEN-LAST:event_jb_agregar_expMouseClicked

    private void jb_agregar_conMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregar_conMouseClicked
        DefaultListModel listaModelo = (DefaultListModel)jL_planetas_con.getModel();
        Planeta mover = (Planeta) listaModelo.getElementAt(jL_planetas_con.getSelectedIndex());
       
       
        DefaultListModel lista = (DefaultListModel)jL_conquistados.getModel();
        lista.addElement(mover);
        jL_conquistados.setModel(lista);
    }//GEN-LAST:event_jb_agregar_conMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_favorito;
    private javax.swing.JComboBox<String> cb_habita_ab;
    private javax.swing.JComboBox<String> cb_habita_caz;
    private javax.swing.JComboBox<String> cb_habita_con;
    private javax.swing.JComboBox<String> cb_habita_exp;
    private javax.swing.JComboBox<String> cb_planetafav_editar;
    private javax.swing.JComboBox<String> cb_planetas;
    private javax.swing.JComboBox<String> cb_planetas_arb;
    private javax.swing.JComboBox<String> cb_raza_ab;
    private javax.swing.JComboBox<String> cb_raza_caz;
    private javax.swing.JComboBox<String> cb_raza_con;
    private javax.swing.JComboBox<String> cb_raza_editar;
    private javax.swing.JComboBox<String> cb_raza_exp;
    private javax.swing.JList<String> jL_alien;
    private javax.swing.JList<String> jL_conquistados;
    private javax.swing.JList<String> jL_explorados;
    private javax.swing.JList<String> jL_planetas;
    private javax.swing.JList<String> jL_planetas_con;
    private javax.swing.JList<String> jL_planetas_disp;
    private javax.swing.JList<String> jL_planetas_disp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton jb_agregar_con;
    private javax.swing.JButton jb_agregar_exp;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_guardar_ab;
    private javax.swing.JButton jb_guardar_caz;
    private javax.swing.JButton jb_guardar_con;
    private javax.swing.JButton jb_guardar_exp;
    private javax.swing.JButton jb_guardar_p;
    private javax.swing.JButton jb_guardar_r;
    private javax.swing.JButton jb_pasar;
    private javax.swing.JButton jb_pasar_editar;
    private javax.swing.JCheckBox jc_agua;
    private javax.swing.JCheckBox jc_amenaza_ab;
    private javax.swing.JCheckBox jc_amenaza_caz;
    private javax.swing.JCheckBox jc_amenaza_con;
    private javax.swing.JCheckBox jc_amenaza_editar;
    private javax.swing.JCheckBox jc_amenaza_exp;
    private javax.swing.JSpinner js_animales;
    private javax.swing.JSpinner js_animales_editar;
    private javax.swing.JSpinner js_edad_ab;
    private javax.swing.JSpinner js_edad_caz;
    private javax.swing.JSpinner js_edad_con;
    private javax.swing.JSpinner js_edad_editar;
    private javax.swing.JSpinner js_edad_exp;
    private javax.swing.JSpinner js_humanos;
    private javax.swing.JSpinner js_humanos_editar;
    private javax.swing.JSpinner js_size;
    private javax.swing.JSpinner js_temperatura;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JTextField tf_nombre_ab;
    private javax.swing.JTextField tf_nombre_caz;
    private javax.swing.JTextField tf_nombre_con;
    private javax.swing.JTextField tf_nombre_editar;
    private javax.swing.JTextField tf_nombre_exp;
    private javax.swing.JTextField tf_nombre_p;
    private javax.swing.JTextField tf_nombre_r;
    // End of variables declaration//GEN-END:variables
}
